/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BasesTagColorsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/base-view.ts
function getBasePath(leaf) {
  var _a, _b, _c, _d, _e;
  const view = leaf.view;
  if ((view == null ? void 0 : view.getViewType()) !== "bases")
    return null;
  return (_e = (_d = (_a = view.file) == null ? void 0 : _a.path) != null ? _d : (_c = (_b = leaf.getViewState()) == null ? void 0 : _b.state) == null ? void 0 : _c.file) != null ? _e : null;
}
function tagLeaf(leaf, basePath) {
  const view = leaf.view;
  const containerEl = view.containerEl;
  if (!containerEl)
    return null;
  const basesView = containerEl.querySelector(".bases-view");
  if (!basesView)
    console.warn("[BasesTagColors] .bases-view selector not found \u2014 Obsidian Bases DOM may have changed");
  const rootEl = basesView != null ? basesView : containerEl;
  rootEl.setAttribute("data-bases-tag-colors-id", basePath);
  return rootEl;
}
function untagLeaf(leaf) {
  const view = leaf.view;
  const containerEl = view == null ? void 0 : view.containerEl;
  if (!containerEl)
    return;
  containerEl.querySelectorAll("[data-bases-tag-colors-id]").forEach((el) => el.removeAttribute("data-bases-tag-colors-id"));
  containerEl.removeAttribute("data-bases-tag-colors-id");
}

// src/types.ts
var DEFAULT_COLOR_CONFIG = {
  version: 1,
  columns: {}
};

// src/config-io.ts
async function listBasesInVault(app) {
  return app.vault.getFiles().filter((f) => f.path.endsWith(".base")).map((f) => f.path).sort();
}
function colorsPathFromBasePath(basePath) {
  return basePath.replace(/\.base$/, ".colors.json");
}
function basePathFromColorsPath(colorsPath) {
  return colorsPath.replace(/\.colors\.json$/, ".base");
}
async function loadConfig(app, basePath) {
  const colorsPath = colorsPathFromBasePath(basePath);
  try {
    const exists = await app.vault.adapter.exists(colorsPath);
    if (!exists)
      return { ...DEFAULT_COLOR_CONFIG };
    const raw = await app.vault.adapter.read(colorsPath);
    const parsed = JSON.parse(raw);
    if (parsed.version !== 1)
      return { ...DEFAULT_COLOR_CONFIG };
    if (typeof parsed.columns !== "object" || parsed.columns === null || Array.isArray(parsed.columns)) {
      return { ...DEFAULT_COLOR_CONFIG };
    }
    return parsed;
  } catch (e) {
    console.warn(`[BasesTagColors] Failed to load config at ${colorsPath}:`, e);
    return { ...DEFAULT_COLOR_CONFIG };
  }
}
async function saveConfig(app, basePath, config) {
  const colorsPath = colorsPathFromBasePath(basePath);
  try {
    await app.vault.adapter.write(colorsPath, JSON.stringify(config, null, 2));
  } catch (e) {
    console.error(`[BasesTagColors] Failed to save config at ${colorsPath}:`, e);
  }
}
function sanitizeValue(text) {
  return text.replace(/\s+/g, "").replace(/[^\wÀ-ſ-]/g, "");
}
function generateColorFromText(sanitized) {
  let hash = 0;
  for (let i = 0; i < sanitized.length; i++) {
    const c = sanitized.charCodeAt(i);
    hash = (hash << 5) - hash + c;
    hash = hash & hash;
  }
  const r = 80 + Math.abs(hash) % 120;
  const g = 80 + Math.abs(hash >> 8) % 120;
  const b = 80 + Math.abs(hash >> 16) % 120;
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
}
async function parseBaseColumns(app, basePath) {
  try {
    const raw = await app.vault.adapter.read(basePath);
    const match = raw.match(/^properties:\s*\n((?:[ \t]+\S[^\n]*\n?)*)/m);
    if (!match)
      return null;
    const keys = [...match[1].matchAll(/^[ \t]+([\w.]+):/gm)].map((m) => m[1]);
    return keys.length ? new Set(keys) : null;
  } catch (e) {
    return null;
  }
}
function seedConfigFromView(viewRoot) {
  const config = { version: 1, columns: {} };
  viewRoot.querySelectorAll(".multi-select-pill").forEach((pill) => {
    var _a, _b, _c;
    const contentEl = pill.querySelector(".multi-select-pill-content");
    const rawText = ((_b = (_a = contentEl == null ? void 0 : contentEl.textContent) != null ? _a : pill.textContent) != null ? _b : "").trim();
    if (!rawText)
      return;
    const tdEl = pill.closest("[data-property]");
    const col = (_c = tdEl == null ? void 0 : tdEl.getAttribute("data-property")) != null ? _c : "*";
    const sanitized = sanitizeValue(rawText);
    if (!sanitized)
      return;
    if (!config.columns[col])
      config.columns[col] = {};
    if (!config.columns[col][rawText]) {
      config.columns[col][rawText] = generateColorFromText(sanitized);
    }
  });
  return config;
}

// src/style-manager.ts
var STYLE_ID = "bases-tag-colors-style";
var StyleManager = class {
  constructor() {
    this.rulesByBase = /* @__PURE__ */ new Map();
    this.styleEl = this.getOrCreate();
  }
  getOrCreate() {
    let el = document.getElementById(STYLE_ID);
    if (!el || !el.isConnected) {
      el = document.createElement("style");
      el.id = STYLE_ID;
      el.type = "text/css";
      document.head.appendChild(el);
    }
    return el;
  }
  setRulesForBase(basePath, config) {
    const rules = [];
    const escapedPath = basePath.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    for (const [col, colorMap] of Object.entries(config.columns)) {
      for (const [rawValue, color] of Object.entries(colorMap)) {
        if (!color || !/^#[0-9a-fA-F]{3}$|^#[0-9a-fA-F]{6}$|^rgba?\(/.test(color))
          continue;
        const sanitized = sanitizeValue(rawValue);
        if (!sanitized)
          continue;
        if (col === "*") {
          rules.push(
            `[data-bases-tag-colors-id="${escapedPath}"] .multi-select-pill[data-blc-value="${sanitized}"] { background-color: ${color} !important; color: white; }`
          );
        } else {
          const escapedCol = col.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
          rules.push(
            `[data-bases-tag-colors-id="${escapedPath}"] .multi-select-pill[data-blc-col="${escapedCol}"][data-blc-value="${sanitized}"] { background-color: ${color} !important; color: white; }`
          );
        }
      }
    }
    this.rulesByBase.set(basePath, rules);
    this.rebuild();
  }
  clearRulesForBase(basePath) {
    this.rulesByBase.delete(basePath);
    this.rebuild();
  }
  clearAll() {
    this.rulesByBase.clear();
    this.styleEl.textContent = "";
  }
  rebuild() {
    const all = [];
    for (const rules of this.rulesByBase.values())
      all.push(...rules);
    this.styleEl.textContent = all.join("\n");
  }
  destroy() {
    this.clearAll();
    this.styleEl.remove();
  }
};

// src/pill-processor.ts
function processBaseView(viewRoot) {
  viewRoot.querySelectorAll(".multi-select-pill").forEach((pill) => {
    var _a, _b;
    const contentEl = pill.querySelector(".multi-select-pill-content");
    const rawText = ((_b = (_a = contentEl == null ? void 0 : contentEl.textContent) != null ? _a : pill.textContent) != null ? _b : "").trim();
    if (!rawText)
      return;
    const sanitized = sanitizeValue(rawText);
    if (!sanitized)
      return;
    pill.setAttribute("data-blc-value", sanitized);
    const tdEl = pill.closest("[data-property]");
    const col = tdEl == null ? void 0 : tdEl.getAttribute("data-property");
    if (col) {
      pill.setAttribute("data-blc-col", col);
    }
  });
}

// src/commands.ts
var import_obsidian = require("obsidian");
async function cmdOpenColorConfig(app) {
  var _a;
  const leaf = app.workspace.activeLeaf;
  if (!leaf || ((_a = leaf.view) == null ? void 0 : _a.getViewType()) !== "bases") {
    new import_obsidian.Notice("Bases Tag Colors: open a .base file first");
    return;
  }
  const basePath = getBasePath(leaf);
  if (!basePath) {
    new import_obsidian.Notice("Bases Tag Colors: could not resolve base file path");
    return;
  }
  const colorsPath = colorsPathFromBasePath(basePath);
  const exists = await app.vault.adapter.exists(colorsPath);
  if (!exists) {
    await app.vault.adapter.write(
      colorsPath,
      JSON.stringify(DEFAULT_COLOR_CONFIG, null, 2)
    );
  }
  await app.workspace.openLinkText(colorsPath, "", false);
}
async function cmdSeedFromCurrentBase(app) {
  var _a, _b;
  const leaf = app.workspace.activeLeaf;
  if (!leaf || ((_a = leaf.view) == null ? void 0 : _a.getViewType()) !== "bases") {
    new import_obsidian.Notice("Bases Tag Colors: open a .base file first");
    return;
  }
  const basePath = getBasePath(leaf);
  if (!basePath) {
    new import_obsidian.Notice("Bases Tag Colors: could not resolve base file path");
    return;
  }
  const view = leaf.view;
  const containerEl = view.containerEl;
  if (!containerEl)
    return;
  const rootEl = (_b = containerEl.querySelector(".bases-view")) != null ? _b : containerEl;
  const seeded = seedConfigFromView(rootEl);
  const totalEntries = Object.values(seeded.columns).reduce(
    (sum, vals) => sum + Object.keys(vals).length,
    0
  );
  await saveConfig(app, basePath, seeded);
  const colorsPath = colorsPathFromBasePath(basePath);
  new import_obsidian.Notice(`Bases Tag Colors: wrote ${totalEntries} entries to ${colorsPath}`);
}
async function cmdReloadColorConfig(app, applyToBase) {
  var _a;
  const leaf = app.workspace.activeLeaf;
  if (!leaf || ((_a = leaf.view) == null ? void 0 : _a.getViewType()) !== "bases") {
    new import_obsidian.Notice("Bases Tag Colors: open a .base file first");
    return;
  }
  const basePath = getBasePath(leaf);
  if (!basePath) {
    new import_obsidian.Notice("Bases Tag Colors: could not resolve base file path");
    return;
  }
  await applyToBase(basePath);
  new import_obsidian.Notice("Bases Tag Colors: config reloaded");
}
async function cmdMigrateFromOldPlugin(app, applyToBase) {
  var _a, _b, _c;
  const leaf = app.workspace.activeLeaf;
  if (!leaf || ((_a = leaf.view) == null ? void 0 : _a.getViewType()) !== "bases") {
    new import_obsidian.Notice("Bases Tag Colors: open a .base file first");
    return;
  }
  const basePath = getBasePath(leaf);
  if (!basePath) {
    new import_obsidian.Notice("Bases Tag Colors: could not resolve base file path");
    return;
  }
  const oldDataPath = ".obsidian/plugins/colored-bases-properties/data.json";
  const oldExists = await app.vault.adapter.exists(oldDataPath);
  if (!oldExists) {
    new import_obsidian.Notice("Bases Tag Colors: colored-bases-properties not found \u2014 nothing to migrate");
    return;
  }
  let oldPillColors = {};
  try {
    const raw = await app.vault.adapter.read(oldDataPath);
    const parsed = JSON.parse(raw);
    oldPillColors = (_b = parsed.pillColors) != null ? _b : {};
  } catch (e) {
    new import_obsidian.Notice("Bases Tag Colors: failed to read old plugin data");
    return;
  }
  const view = leaf.view;
  const containerEl = view.containerEl;
  if (!containerEl)
    return;
  const rootEl = (_c = containerEl.querySelector(".bases-view")) != null ? _c : containerEl;
  const visibleValues = /* @__PURE__ */ new Set();
  rootEl.querySelectorAll(".multi-select-pill").forEach((pill) => {
    var _a2, _b2;
    const contentEl = pill.querySelector(".multi-select-pill-content");
    const rawText = ((_b2 = (_a2 = contentEl == null ? void 0 : contentEl.textContent) != null ? _a2 : pill.textContent) != null ? _b2 : "").trim();
    if (rawText)
      visibleValues.add(rawText);
  });
  const existing = await loadConfig(app, basePath);
  let migrated = 0;
  let total = 0;
  for (const rawText of visibleValues) {
    total++;
    if (oldPillColors[rawText]) {
      if (!existing.columns["*"])
        existing.columns["*"] = {};
      existing.columns["*"][rawText] = oldPillColors[rawText];
      migrated++;
    }
  }
  await saveConfig(app, basePath, existing);
  await applyToBase(basePath);
  const colorsPath = colorsPathFromBasePath(basePath);
  new import_obsidian.Notice(`Bases Tag Colors: migrated ${migrated} of ${total} values to ${colorsPath}`);
}

// src/settings-tab.ts
var import_obsidian2 = require("obsidian");
var BasesTagColorsSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.selectedBase = "";
    this.config = { version: 1, columns: {} };
    this.searchQuery = "";
    this.debounceTimer = null;
    this.plugin = plugin;
  }
  hide() {
    if (this.debounceTimer !== null) {
      window.clearTimeout(this.debounceTimer);
      this.debounceTimer = null;
    }
  }
  async display() {
    var _a;
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("blc-settings");
    const hero = containerEl.createDiv({ cls: "blc-hero" });
    hero.createEl("p", { text: "BASES TAG COLORS", cls: "blc-hero-eyebrow" });
    hero.createEl("h1", { text: "Bring life to your tags.", cls: "blc-hero-title" });
    hero.createEl("p", { text: "v1.1 By Oleg Brovchenko", cls: "blc-hero-meta" });
    const headerEl = containerEl.createDiv({ cls: "blc-header" });
    const selectorWrapper = headerEl.createDiv({ cls: "blc-selector-wrapper" });
    selectorWrapper.createEl("label", { text: "Base:", cls: "blc-label" });
    const select = selectorWrapper.createEl("select", { cls: "blc-base-select" });
    const importBtn = headerEl.createEl("button", { text: "Import from active base", cls: "blc-import-btn mod-cta" });
    const searchInput = containerEl.createEl("input", {
      type: "text",
      placeholder: "Search values\u2026",
      cls: "blc-search"
    });
    containerEl.createEl("div", { text: "Colors", cls: "blc-section-label" });
    const listEl = containerEl.createDiv({ cls: "blc-list" });
    containerEl.createEl("div", { text: "Add value", cls: "blc-section-label" });
    const addRowEl = containerEl.createDiv({ cls: "blc-add-row" });
    this.buildAddRow(addRowEl, listEl);
    const bases = await listBasesInVault(this.app);
    if (bases.length === 0) {
      select.createEl("option", { text: "No .base files found", value: "" });
      importBtn.disabled = true;
      return;
    }
    const activeLeaf = this.app.workspace.activeLeaf;
    const activeBase = activeLeaf ? getBasePath(activeLeaf) : null;
    for (const b of bases) {
      const opt = select.createEl("option", { text: b, value: b });
      if (b === activeBase)
        opt.selected = true;
    }
    this.selectedBase = activeBase && bases.includes(activeBase) ? activeBase : bases[0];
    select.value = this.selectedBase;
    this.config = await loadConfig(this.app, this.selectedBase);
    this.renderValueList(listEl);
    select.addEventListener("change", async () => {
      this.selectedBase = select.value;
      this.config = await loadConfig(this.app, this.selectedBase);
      this.searchQuery = "";
      searchInput.value = "";
      this.renderValueList(listEl);
    });
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value.toLowerCase();
      this.filterRows(listEl);
    });
    importBtn.addEventListener("click", async () => {
      var _a2, _b;
      const leaf = this.app.workspace.activeLeaf;
      if (!leaf || ((_a2 = leaf.view) == null ? void 0 : _a2.getViewType()) !== "bases") {
        importBtn.title = "No bases view open";
        return;
      }
      const activeBase2 = getBasePath(leaf);
      if (activeBase2 !== this.selectedBase) {
        importBtn.title = `Active base doesn't match \u2014 open "${this.selectedBase}" first`;
        new import_obsidian2.Notice(`Import aborted: active view is a different base. Click the "${this.selectedBase}" tab first.`);
        return;
      }
      const view = leaf.view;
      const containerEl2 = view.containerEl;
      if (!containerEl2)
        return;
      const rootEl = (_b = containerEl2.querySelector(".bases-view")) != null ? _b : containerEl2;
      const seeded = seedConfigFromView(rootEl);
      const allowedCols = await parseBaseColumns(this.app, this.selectedBase);
      for (const [col, vals] of Object.entries(seeded.columns)) {
        if (allowedCols && col !== "*" && !allowedCols.has(col))
          continue;
        if (!this.config.columns[col])
          this.config.columns[col] = {};
        for (const [rawVal, color] of Object.entries(vals)) {
          if (!this.config.columns[col][rawVal]) {
            this.config.columns[col][rawVal] = color;
          }
        }
      }
      await this.saveAndApply();
      this.renderValueList(listEl);
    });
    this.updateImportBtnState(importBtn);
    containerEl.createEl("hr", { cls: "blc-landing-divider" });
    const featuresSection = containerEl.createDiv({ cls: "blc-features" });
    featuresSection.createEl("p", { text: "WHAT IT DOES", cls: "blc-section-eyebrow" });
    const grid = featuresSection.createDiv({ cls: "blc-features-grid" });
    [
      { title: "Auto base detection", body: "Automatically detects your active base." },
      { title: "Visual settings UI", body: "Color picker, hex input, search bar." },
      { title: "Live in 100ms", body: "Edit the color, real time update." },
      { title: "Per-base palettes", body: "Each .base file gets a sibling .colors.json." }
    ].forEach((f) => {
      const item = grid.createDiv({ cls: "blc-feature-item" });
      item.createEl("h3", { text: f.title, cls: "blc-feature-title" });
      item.createEl("p", { text: f.body, cls: "blc-feature-body" });
    });
    const problemSection = containerEl.createDiv({ cls: "blc-text-section" });
    problemSection.createEl("p", { text: "THE PROBLEM", cls: "blc-section-eyebrow" });
    problemSection.createEl("p", { text: "Obsidian Bases have zero native pill colors. It makes reading extremely hard, especially annoying if you are coming from Notion and you are used to having colors on your tags.", cls: "blc-text-body" });
    const previewSection = containerEl.createDiv({ cls: "blc-text-section" });
    previewSection.createEl("p", { text: "PREVIEW", cls: "blc-section-eyebrow" });
    const windowFrame = previewSection.createDiv({ cls: "blc-window-frame" });
    const windowChrome = windowFrame.createDiv({ cls: "blc-window-chrome" });
    const dotsWrap = windowChrome.createDiv({ cls: "blc-window-dots" });
    dotsWrap.createDiv({ cls: "blc-dot blc-dot-red" });
    dotsWrap.createDiv({ cls: "blc-dot blc-dot-yellow" });
    dotsWrap.createDiv({ cls: "blc-dot blc-dot-green" });
    windowChrome.createEl("span", { text: "YouTube Ideas.base", cls: "blc-window-title" });
    const img = windowFrame.createEl("img", { cls: "blc-preview-img", attr: { alt: "Bases Tag Colors in action" } });
    const pluginDir = (_a = this.plugin.manifest.dir) != null ? _a : ".obsidian/plugins/bases-tag-colors";
    img.src = this.app.vault.adapter.getResourcePath(`${pluginDir}/preview.png`);
    containerEl.createEl("p", { text: "Enjoy! \u2014 Oleg Brovchenko", cls: "blc-signoff" });
  }
  updateImportBtnState(btn) {
    var _a;
    const leaf = this.app.workspace.activeLeaf;
    const isBasesView = ((_a = leaf == null ? void 0 : leaf.view) == null ? void 0 : _a.getViewType()) === "bases";
    btn.disabled = !isBasesView;
    btn.title = isBasesView ? "Import all visible pill values from the active base" : "No bases view open";
  }
  renderValueList(listEl) {
    listEl.empty();
    const entries = [];
    for (const [col, vals] of Object.entries(this.config.columns)) {
      for (const [rawValue, color] of Object.entries(vals)) {
        entries.push({ col, rawValue, color });
      }
    }
    const valuesWithSpecificCol = new Set(
      entries.filter((e) => e.col !== "*").map((e) => e.rawValue)
    );
    const deduped = entries.filter((e) => !(e.col === "*" && valuesWithSpecificCol.has(e.rawValue)));
    deduped.sort((a, b) => {
      if (a.col === "*" && b.col !== "*")
        return -1;
      if (a.col !== "*" && b.col === "*")
        return 1;
      if (a.col !== b.col)
        return a.col.localeCompare(b.col);
      return a.rawValue.localeCompare(b.rawValue);
    });
    if (deduped.length === 0) {
      listEl.createEl("p", { text: "No colors configured. Import from active base or add manually below.", cls: "blc-empty" });
      return;
    }
    for (const entry of deduped) {
      this.buildRow(listEl, entry.col, entry.rawValue, entry.color);
    }
    this.filterRows(listEl);
  }
  buildRow(listEl, col, rawValue, color) {
    const row = listEl.createDiv({ cls: "blc-row" });
    row.dataset.col = col;
    row.dataset.value = rawValue.toLowerCase();
    const pillPreview = row.createEl("span", { text: rawValue, cls: "blc-pill-preview" });
    pillPreview.style.backgroundColor = color;
    row.createEl("span", { text: col === "*" ? "any column" : col, cls: "blc-col-badge" });
    row.createDiv({ cls: "blc-spacer" });
    const picker = row.createEl("input", { cls: "blc-color-picker" });
    picker.type = "color";
    picker.value = color;
    const hexInput = row.createEl("input", { cls: "blc-hex-input" });
    hexInput.type = "text";
    hexInput.maxLength = 7;
    hexInput.value = color;
    hexInput.placeholder = "#rrggbb";
    const removeBtn = row.createEl("button", { text: "\xD7", cls: "blc-remove-btn" });
    picker.addEventListener("input", () => {
      hexInput.value = picker.value;
      pillPreview.style.backgroundColor = picker.value;
      this.setColor(col, rawValue, picker.value);
      this.debouncedSaveApply();
    });
    hexInput.addEventListener("blur", () => {
      const val = hexInput.value.trim();
      if (/^#[0-9a-fA-F]{6}$/.test(val)) {
        picker.value = val;
        pillPreview.style.backgroundColor = val;
        this.setColor(col, rawValue, val);
        this.saveAndApply();
      } else {
        hexInput.value = picker.value;
      }
    });
    removeBtn.addEventListener("click", async () => {
      this.deleteColor(col, rawValue);
      await this.saveAndApply();
      row.remove();
    });
  }
  buildAddRow(addRowEl, listEl) {
    const nameInput = addRowEl.createEl("input", { cls: "blc-add-name" });
    nameInput.type = "text";
    nameInput.placeholder = "Value name";
    const picker = addRowEl.createEl("input", { cls: "blc-color-picker" });
    picker.type = "color";
    picker.value = "#78b7b8";
    const hexInput = addRowEl.createEl("input", { cls: "blc-hex-input" });
    hexInput.type = "text";
    hexInput.maxLength = 7;
    hexInput.value = "#78b7b8";
    hexInput.placeholder = "#rrggbb";
    picker.addEventListener("input", () => {
      hexInput.value = picker.value;
    });
    hexInput.addEventListener("blur", () => {
      if (/^#[0-9a-fA-F]{6}$/.test(hexInput.value.trim())) {
        picker.value = hexInput.value.trim();
      } else {
        hexInput.value = picker.value;
      }
    });
    const addBtn = addRowEl.createEl("button", { text: "+ Add", cls: "blc-add-btn" });
    addBtn.addEventListener("click", async () => {
      const name = nameInput.value.trim();
      if (!name)
        return;
      const color = picker.value;
      if (!this.config.columns["*"])
        this.config.columns["*"] = {};
      this.config.columns["*"][name] = color;
      await this.saveAndApply();
      this.buildRow(listEl, "*", name, color);
      this.filterRows(listEl);
      nameInput.value = "";
      picker.value = "#78b7b8";
      hexInput.value = "#78b7b8";
    });
  }
  filterRows(listEl) {
    const q = this.searchQuery;
    listEl.querySelectorAll(".blc-row").forEach((row) => {
      var _a, _b;
      const valueText = (_a = row.dataset.value) != null ? _a : "";
      const colText = (_b = row.dataset.col) != null ? _b : "";
      const matches = !q || valueText.includes(q) || colText.includes(q);
      row.style.display = matches ? "" : "none";
    });
  }
  setColor(col, rawValue, color) {
    if (!this.config.columns[col])
      this.config.columns[col] = {};
    this.config.columns[col][rawValue] = color;
  }
  deleteColor(col, rawValue) {
    if (!this.config.columns[col])
      return;
    delete this.config.columns[col][rawValue];
    if (Object.keys(this.config.columns[col]).length === 0) {
      delete this.config.columns[col];
    }
  }
  debouncedSaveApply() {
    if (this.debounceTimer !== null)
      window.clearTimeout(this.debounceTimer);
    this.debounceTimer = window.setTimeout(() => {
      this.debounceTimer = null;
      this.saveAndApply();
    }, 150);
  }
  async saveAndApply() {
    if (!this.selectedBase)
      return;
    await saveConfig(this.app, this.selectedBase, this.config);
    await this.plugin.applyToBase(this.selectedBase);
  }
};

// main.ts
var BasesTagColorsPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.activeLeaves = /* @__PURE__ */ new Map();
    this.layoutDebounce = null;
    this.colorsModifyDebounce = /* @__PURE__ */ new Map();
  }
  async onload() {
    this.styles = new StyleManager();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        var _a;
        if (!leaf)
          return;
        if (((_a = leaf.view) == null ? void 0 : _a.getViewType()) === "bases") {
          this.activateLeaf(leaf);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        if (this.layoutDebounce !== null)
          window.clearTimeout(this.layoutDebounce);
        this.layoutDebounce = window.setTimeout(() => {
          this.layoutDebounce = null;
          this.syncLeaves();
        }, 50);
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (!(file instanceof import_obsidian3.TFile))
          return;
        if (!file.path.endsWith(".colors.json"))
          return;
        const prev = this.colorsModifyDebounce.get(file.path);
        if (prev !== void 0)
          window.clearTimeout(prev);
        const timer = window.setTimeout(() => {
          this.colorsModifyDebounce.delete(file.path);
          const basePath = basePathFromColorsPath(file.path);
          this.applyToBase(basePath);
        }, 100);
        this.colorsModifyDebounce.set(file.path, timer);
      })
    );
    this.addCommand({
      id: "open-color-config",
      name: "Open color config for current base",
      callback: () => cmdOpenColorConfig(this.app)
    });
    this.addCommand({
      id: "seed-from-current-base",
      name: "Seed config from current base values",
      callback: () => cmdSeedFromCurrentBase(this.app)
    });
    this.addCommand({
      id: "reload-color-config",
      name: "Reload color config",
      callback: () => cmdReloadColorConfig(this.app, this.applyToBase.bind(this))
    });
    this.addCommand({
      id: "migrate-from-colored-bases-properties",
      name: "Migrate from colored-bases-properties (current base)",
      callback: () => cmdMigrateFromOldPlugin(this.app, this.applyToBase.bind(this))
    });
    this.addSettingTab(new BasesTagColorsSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => this.syncLeaves());
  }
  // D3: load config, inject CSS, stamp pills, wire observer
  async activateLeaf(leaf) {
    const basePath = getBasePath(leaf);
    if (!basePath) {
      console.warn("[BasesTagColors] bases view active but path unavailable");
      return;
    }
    const existing = this.activeLeaves.get(leaf);
    if (existing && existing.basePath === basePath) {
      await this.applyToBase(basePath);
      return;
    }
    if (existing)
      this.deactivateLeaf(leaf);
    const rootEl = tagLeaf(leaf, basePath);
    if (!rootEl)
      return;
    const config = await loadConfig(this.app, basePath);
    this.styles.setRulesForBase(basePath, config);
    processBaseView(rootEl);
    const observer = new MutationObserver((mutations) => {
      const hasPills = mutations.some(
        (m) => m.type === "childList" && Array.from(m.addedNodes).some((node) => {
          var _a;
          if (node.nodeType !== Node.ELEMENT_NODE)
            return false;
          const el = node;
          return el.classList.contains("multi-select-pill") || ((_a = el.querySelector) == null ? void 0 : _a.call(el, ".multi-select-pill")) !== null;
        })
      );
      if (hasPills)
        processBaseView(rootEl);
    });
    observer.observe(rootEl, { childList: true, subtree: true });
    this.activeLeaves.set(leaf, { basePath, rootEl, observer });
  }
  deactivateLeaf(leaf) {
    const state = this.activeLeaves.get(leaf);
    if (!state)
      return;
    state.observer.disconnect();
    state.rootEl.querySelectorAll("[data-blc-value], [data-blc-col]").forEach((el) => {
      el.removeAttribute("data-blc-value");
      el.removeAttribute("data-blc-col");
    });
    untagLeaf(leaf);
    this.activeLeaves.delete(leaf);
    const stillOpen = [...this.activeLeaves.values()].some((s) => s.basePath === state.basePath);
    if (!stillOpen)
      this.styles.clearRulesForBase(state.basePath);
  }
  // Re-tag + re-apply all current bases leaves; clean up closed ones
  syncLeaves() {
    const current = new Set(this.app.workspace.getLeavesOfType("bases"));
    for (const leaf of [...this.activeLeaves.keys()]) {
      if (!current.has(leaf))
        this.deactivateLeaf(leaf);
    }
    for (const leaf of current) {
      if (!this.activeLeaves.has(leaf))
        this.activateLeaf(leaf);
    }
  }
  // D3: re-apply styles + re-process pills for all leaves showing basePath.
  // Re-queries rootEl on every call — guards against DOM refresh (e.g. after Settings close).
  async applyToBase(basePath) {
    const config = await loadConfig(this.app, basePath);
    this.styles.setRulesForBase(basePath, config);
    for (const [leaf, state] of this.activeLeaves.entries()) {
      if (state.basePath !== basePath)
        continue;
      const freshRoot = tagLeaf(leaf, basePath);
      if (!freshRoot)
        continue;
      if (freshRoot !== state.rootEl) {
        state.observer.disconnect();
        state.rootEl = freshRoot;
        const obs = new MutationObserver((mutations) => {
          const hasPills = mutations.some(
            (m) => m.type === "childList" && Array.from(m.addedNodes).some((node) => {
              var _a;
              if (node.nodeType !== Node.ELEMENT_NODE)
                return false;
              const el = node;
              return el.classList.contains("multi-select-pill") || ((_a = el.querySelector) == null ? void 0 : _a.call(el, ".multi-select-pill")) !== null;
            })
          );
          if (hasPills)
            processBaseView(freshRoot);
        });
        obs.observe(freshRoot, { childList: true, subtree: true });
        state.observer = obs;
      }
      processBaseView(state.rootEl);
    }
  }
  onunload() {
    if (this.layoutDebounce !== null) {
      window.clearTimeout(this.layoutDebounce);
      this.layoutDebounce = null;
    }
    for (const timer of this.colorsModifyDebounce.values())
      window.clearTimeout(timer);
    this.colorsModifyDebounce.clear();
    for (const leaf of [...this.activeLeaves.keys()])
      this.deactivateLeaf(leaf);
    this.styles.destroy();
  }
};
