/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BasesTagColorsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/base-view.ts
function getBasePath(leaf) {
  var _a, _b, _c, _d, _e;
  const view = leaf.view;
  if ((view == null ? void 0 : view.getViewType()) !== "bases")
    return null;
  return (_e = (_d = (_a = view.file) == null ? void 0 : _a.path) != null ? _d : (_c = (_b = leaf.getViewState()) == null ? void 0 : _b.state) == null ? void 0 : _c.file) != null ? _e : null;
}
function tagLeaf(leaf, basePath) {
  const view = leaf.view;
  const containerEl = view.containerEl;
  if (!containerEl)
    return null;
  const basesView = containerEl.querySelector(".bases-view");
  if (!basesView)
    console.warn("[BasesTagColors] .bases-view selector not found \u2014 Obsidian Bases DOM may have changed");
  const rootEl = basesView != null ? basesView : containerEl;
  rootEl.setAttribute("data-bases-tag-colors-id", basePath);
  return rootEl;
}
function untagLeaf(leaf) {
  const view = leaf.view;
  const containerEl = view == null ? void 0 : view.containerEl;
  if (!containerEl)
    return;
  containerEl.querySelectorAll("[data-bases-tag-colors-id]").forEach((el) => el.removeAttribute("data-bases-tag-colors-id"));
  containerEl.removeAttribute("data-bases-tag-colors-id");
}

// src/embed-view.ts
var EMBED_SELECTOR = ".internal-embed.bases-embed";
function containsBasesEmbed(el) {
  var _a, _b;
  return !!(((_a = el.matches) == null ? void 0 : _a.call(el, EMBED_SELECTOR)) || ((_b = el.querySelector) == null ? void 0 : _b.call(el, EMBED_SELECTOR)));
}
function tagEmbeds(app, containerEl, sourcePath) {
  const roots = /* @__PURE__ */ new Map();
  containerEl.querySelectorAll(EMBED_SELECTOR).forEach((embedEl) => {
    var _a;
    const src = embedEl.getAttribute("src");
    if (!src)
      return;
    const linkpath = src.split("#")[0];
    const file = app.metadataCache.getFirstLinkpathDest(linkpath, sourcePath);
    if (!file)
      return;
    const rootEl = (_a = embedEl.querySelector(".bases-view")) != null ? _a : embedEl;
    rootEl.setAttribute("data-bases-tag-colors-id", file.path);
    const list = roots.get(file.path);
    if (list) {
      list.push(rootEl);
    } else {
      roots.set(file.path, [rootEl]);
    }
  });
  return roots;
}

// src/types.ts
var DEFAULT_COLOR_CONFIG = {
  version: 1,
  columns: {}
};
var DEFAULT_SETTINGS = {
  customShape: true,
  paddingX: 6,
  paddingY: 2,
  borderRadius: 4,
  autoColor: true,
  propertiesColor: true
};

// src/config-io.ts
async function listBasesInVault(app) {
  return app.vault.getFiles().filter((f) => f.path.endsWith(".base")).map((f) => f.path).sort();
}
function colorsPathFromBasePath(basePath) {
  return basePath.replace(/\.base$/, ".colors.json");
}
function basePathFromColorsPath(colorsPath) {
  return colorsPath.replace(/\.colors\.json$/, ".base");
}
async function loadConfig(app, basePath) {
  const colorsPath = colorsPathFromBasePath(basePath);
  try {
    const exists = await app.vault.adapter.exists(colorsPath);
    if (!exists)
      return { ...DEFAULT_COLOR_CONFIG };
    const raw = await app.vault.adapter.read(colorsPath);
    const parsed = JSON.parse(raw);
    if (parsed.version !== 1)
      return { ...DEFAULT_COLOR_CONFIG };
    if (typeof parsed.columns !== "object" || parsed.columns === null || Array.isArray(parsed.columns)) {
      return { ...DEFAULT_COLOR_CONFIG };
    }
    return parsed;
  } catch (e) {
    console.warn(`[BasesTagColors] Failed to load config at ${colorsPath}:`, e);
    return { ...DEFAULT_COLOR_CONFIG };
  }
}
async function saveConfig(app, basePath, config) {
  const colorsPath = colorsPathFromBasePath(basePath);
  try {
    await app.vault.adapter.write(colorsPath, JSON.stringify(config, null, 2));
  } catch (e) {
    console.error(`[BasesTagColors] Failed to save config at ${colorsPath}:`, e);
  }
}
function sanitizeValue(text) {
  return text.replace(/\s+/g, "").replace(/[^\wÀ-ſ-]/g, "");
}
function generateColorFromText(sanitized) {
  let hash = 0;
  for (let i = 0; i < sanitized.length; i++) {
    const c = sanitized.charCodeAt(i);
    hash = (hash << 5) - hash + c;
    hash = hash & hash;
  }
  const r = 80 + Math.abs(hash) % 120;
  const g = 80 + Math.abs(hash >> 8) % 120;
  const b = 80 + Math.abs(hash >> 16) % 120;
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
}
async function parseBaseColumns(app, basePath) {
  try {
    const raw = await app.vault.adapter.read(basePath);
    const match = raw.match(/^properties:\s*\n((?:[ \t]+\S[^\n]*\n?)*)/m);
    if (!match)
      return null;
    const keys = [...match[1].matchAll(/^[ \t]+([\w.]+):/gm)].map((m) => m[1]);
    return keys.length ? new Set(keys) : null;
  } catch (e) {
    return null;
  }
}
function seedConfigFromView(viewRoot) {
  const config = { version: 1, columns: {} };
  viewRoot.querySelectorAll(".multi-select-pill").forEach((pill) => {
    var _a, _b, _c;
    const contentEl = pill.querySelector(".multi-select-pill-content");
    const rawText = ((_b = (_a = contentEl == null ? void 0 : contentEl.textContent) != null ? _a : pill.textContent) != null ? _b : "").trim();
    if (!rawText)
      return;
    const tdEl = pill.closest("[data-property]");
    const col = (_c = tdEl == null ? void 0 : tdEl.getAttribute("data-property")) != null ? _c : "*";
    const sanitized = sanitizeValue(rawText);
    if (!sanitized)
      return;
    if (!config.columns[col])
      config.columns[col] = {};
    if (!config.columns[col][rawText]) {
      config.columns[col][rawText] = generateColorFromText(sanitized);
    }
  });
  return config;
}

// src/style-manager.ts
function textColorFor(color) {
  let r, g, b;
  const hex = color.match(/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/);
  const rgb = color.match(/^rgba?\(\s*(\d+)[\s,]+(\d+)[\s,]+(\d+)/);
  if (hex) {
    let h = hex[1];
    if (h.length === 3)
      h = h.split("").map((c) => c + c).join("");
    r = parseInt(h.slice(0, 2), 16);
    g = parseInt(h.slice(2, 4), 16);
    b = parseInt(h.slice(4, 6), 16);
  } else if (rgb) {
    r = Number(rgb[1]);
    g = Number(rgb[2]);
    b = Number(rgb[3]);
  } else {
    return "white";
  }
  return (r * 299 + g * 587 + b * 114) / 1e3 >= 150 ? "#1e1e1e" : "white";
}
var COLOR_RE = /^(#[0-9a-fA-F]{3}|#[0-9a-fA-F]{6}|rgba?\(\s*[\d.,%\s/]+\))$/;
function parseColumns(config) {
  const columns = /* @__PURE__ */ new Map();
  if (typeof config.columns !== "object" || config.columns === null)
    return columns;
  for (const [col, colorMap] of Object.entries(config.columns)) {
    if (typeof colorMap !== "object" || colorMap === null)
      continue;
    for (const [rawValue, color] of Object.entries(colorMap)) {
      if (typeof color !== "string" || !COLOR_RE.test(color))
        continue;
      const sanitized = sanitizeValue(rawValue);
      if (!sanitized)
        continue;
      let values = columns.get(col);
      if (!values) {
        values = /* @__PURE__ */ new Map();
        columns.set(col, values);
      }
      values.set(sanitized, color);
    }
  }
  return columns;
}
var StyleManager = class {
  constructor() {
    this.configByBase = /* @__PURE__ */ new Map();
    // basePath → (sanitized value → generated color); a configured color always
    // wins over these — precedence is explicit in resolveBaseColor
    this.autoColorsByBase = /* @__PURE__ */ new Map();
    // Note Properties panel: configured colors (merged across all bases) + auto colors
    this.propertyConfig = /* @__PURE__ */ new Map();
    this.propertyAutoColors = /* @__PURE__ */ new Map();
  }
  setColorsForBase(basePath, config) {
    this.configByBase.set(basePath, parseColumns(config));
    this.repaintBase(basePath);
  }
  // Global pill shape (padding / border-radius), applied to ALL pills inside
  // tagged bases views — and the note Properties panel when that coloring is
  // on — so rows stay uniform whether or not a pill is colored. The rules live
  // in styles.css, gated on body classes; only the three size variables are
  // set here. They zero Obsidian's --pill-padding-x on purpose: core feeds it
  // into the content's margin-inline-start AND the remove button's
  // margin-inline-end, so leaving it set doubles the horizontal cost on top
  // of our own padding.
  setShape(shape) {
    const body = document.body;
    body.toggleClass("blc-shape", shape.customShape);
    body.toggleClass("blc-shape-props", shape.customShape && shape.propertiesColor);
    if (shape.customShape) {
      body.setCssProps({
        "--blc-px": `${Math.round(shape.paddingX)}px`,
        "--blc-py": `${Math.round(shape.paddingY)}px`,
        "--blc-br": `${Math.round(shape.borderRadius)}px`
      });
    } else {
      body.setCssProps({ "--blc-px": "", "--blc-py": "", "--blc-br": "" });
    }
  }
  clearColorsForBase(basePath) {
    this.configByBase.delete(basePath);
    this.autoColorsByBase.delete(basePath);
    this.repaintBase(basePath);
  }
  // Register newly-seen pill values for a base; generates a stable hash color
  // for each. On new values, repaints EVERY view of the base — a second pane
  // showing the same base must pick them up now, not on its next mutation.
  addAutoValuesForBase(basePath, sanitizedValues) {
    let colors = this.autoColorsByBase.get(basePath);
    if (!colors) {
      colors = /* @__PURE__ */ new Map();
      this.autoColorsByBase.set(basePath, colors);
    }
    let changed = false;
    for (const v of sanitizedValues) {
      if (!colors.has(v)) {
        colors.set(v, generateColorFromText(v));
        changed = true;
      }
    }
    if (changed)
      this.repaintBase(basePath);
  }
  clearAllAutoColors() {
    this.autoColorsByBase.clear();
    this.propertyAutoColors.clear();
    this.repaintAll();
  }
  // Colors for the note Properties panel, merged from every base's config.
  // Column-specific entries match the property key; '*' entries match any.
  // Later bases overwrite earlier on collisions.
  setPropertyColors(configs) {
    const merged = /* @__PURE__ */ new Map();
    for (const config of configs) {
      for (const [col, values] of parseColumns(config).entries()) {
        let target = merged.get(col);
        if (!target) {
          target = /* @__PURE__ */ new Map();
          merged.set(col, target);
        }
        for (const [value, color] of values.entries())
          target.set(value, color);
      }
    }
    this.propertyConfig = merged;
    this.paintProperties();
  }
  // Painting is the caller's job (processPropertyPills always paints after)
  addPropertyAutoValues(sanitizedValues) {
    for (const v of sanitizedValues) {
      if (!this.propertyAutoColors.has(v)) {
        this.propertyAutoColors.set(v, generateColorFromText(v));
      }
    }
  }
  clearPropertyColors() {
    this.propertyConfig = /* @__PURE__ */ new Map();
    this.propertyAutoColors.clear();
    this.paintProperties();
  }
  // ── Painting ─────────────────────────────────────────────────────────
  paintView(rootEl, basePath) {
    rootEl.querySelectorAll(".multi-select-pill[data-blc-value]").forEach((pill) => {
      const value = pill.getAttribute("data-blc-value");
      if (!value)
        return;
      const col = pill.getAttribute("data-blc-col");
      this.applyPaint(pill, this.resolveBaseColor(basePath, col, value));
    });
  }
  // Column matching rides the panel's own data-property-key attribute
  paintProperties() {
    document.body.querySelectorAll(".metadata-property .multi-select-pill[data-blc-value]").forEach((pill) => {
      var _a, _b;
      const value = pill.getAttribute("data-blc-value");
      if (!value)
        return;
      const key = (_b = (_a = pill.closest(".metadata-property")) == null ? void 0 : _a.getAttribute("data-property-key")) != null ? _b : null;
      this.applyPaint(pill, this.resolvePropertyColor(key, value));
    });
  }
  unpaintPill(pill) {
    pill.removeClass("blc-colored");
    pill.setCssProps({ "--blc-bg": "", "--blc-fg": "" });
  }
  // Precedence: configured column-specific > configured '*' > auto
  resolveBaseColor(basePath, col, value) {
    var _a, _b, _c, _d;
    const config = this.configByBase.get(basePath);
    if (config) {
      const specific = col ? (_a = config.get(col)) == null ? void 0 : _a.get(value) : void 0;
      if (specific)
        return specific;
      const any = (_b = config.get("*")) == null ? void 0 : _b.get(value);
      if (any)
        return any;
    }
    return (_d = (_c = this.autoColorsByBase.get(basePath)) == null ? void 0 : _c.get(value)) != null ? _d : null;
  }
  resolvePropertyColor(key, value) {
    var _a, _b, _c;
    const specific = key ? (_a = this.propertyConfig.get(key)) == null ? void 0 : _a.get(value) : void 0;
    if (specific)
      return specific;
    const any = (_b = this.propertyConfig.get("*")) == null ? void 0 : _b.get(value);
    if (any)
      return any;
    return (_c = this.propertyAutoColors.get(value)) != null ? _c : null;
  }
  applyPaint(pill, color) {
    if (color) {
      pill.addClass("blc-colored");
      pill.setCssProps({ "--blc-bg": color, "--blc-fg": textColorFor(color) });
    } else if (pill.hasClass("blc-colored")) {
      this.unpaintPill(pill);
    }
  }
  baseRoots() {
    return Array.from(document.querySelectorAll("[data-bases-tag-colors-id]"));
  }
  repaintBase(basePath) {
    for (const root of this.baseRoots()) {
      if (root.getAttribute("data-bases-tag-colors-id") === basePath) {
        this.paintView(root, basePath);
      }
    }
  }
  repaintAll() {
    for (const root of this.baseRoots()) {
      const basePath = root.getAttribute("data-bases-tag-colors-id");
      if (basePath)
        this.paintView(root, basePath);
    }
    this.paintProperties();
  }
  destroy() {
    this.configByBase.clear();
    this.autoColorsByBase.clear();
    this.propertyConfig = /* @__PURE__ */ new Map();
    this.propertyAutoColors.clear();
    document.querySelectorAll(".blc-colored").forEach((pill) => this.unpaintPill(pill));
    document.body.removeClass("blc-shape", "blc-shape-props");
    document.body.setCssProps({ "--blc-px": "", "--blc-py": "", "--blc-br": "" });
  }
};

// src/pill-processor.ts
function processBaseView(viewRoot) {
  const values = [];
  viewRoot.querySelectorAll(".multi-select-pill").forEach((pill) => {
    var _a, _b;
    const contentEl = pill.querySelector(".multi-select-pill-content");
    const rawText = ((_b = (_a = contentEl == null ? void 0 : contentEl.textContent) != null ? _a : pill.textContent) != null ? _b : "").trim();
    if (!rawText)
      return;
    const sanitized = sanitizeValue(rawText);
    if (!sanitized)
      return;
    pill.setAttribute("data-blc-value", sanitized);
    values.push(sanitized);
    const tdEl = pill.closest("[data-property]");
    const col = tdEl == null ? void 0 : tdEl.getAttribute("data-property");
    if (col) {
      pill.setAttribute("data-blc-col", col);
    }
  });
  return values;
}

// src/commands.ts
var import_obsidian = require("obsidian");
async function cmdOpenColorConfig(app) {
  var _a, _b;
  const leaf = app.workspace.activeLeaf;
  if (!leaf || ((_a = leaf.view) == null ? void 0 : _a.getViewType()) !== "bases") {
    new import_obsidian.Notice("Bases Tag Colors: open a .base file first");
    return;
  }
  const basePath = getBasePath(leaf);
  if (!basePath) {
    new import_obsidian.Notice("Bases Tag Colors: could not resolve base file path");
    return;
  }
  const colorsPath = colorsPathFromBasePath(basePath);
  const exists = await app.vault.adapter.exists(colorsPath);
  if (!exists) {
    await app.vault.adapter.write(
      colorsPath,
      JSON.stringify(DEFAULT_COLOR_CONFIG, null, 2)
    );
  }
  try {
    await app.workspace.openLinkText(colorsPath, "", false);
  } catch (e) {
    const appWithDefault = app;
    await ((_b = appWithDefault.openWithDefaultApp) == null ? void 0 : _b.call(appWithDefault, colorsPath));
  }
}
async function cmdSeedFromCurrentBase(app) {
  var _a, _b;
  const leaf = app.workspace.activeLeaf;
  if (!leaf || ((_a = leaf.view) == null ? void 0 : _a.getViewType()) !== "bases") {
    new import_obsidian.Notice("Bases Tag Colors: open a .base file first");
    return;
  }
  const basePath = getBasePath(leaf);
  if (!basePath) {
    new import_obsidian.Notice("Bases Tag Colors: could not resolve base file path");
    return;
  }
  const view = leaf.view;
  const containerEl = view.containerEl;
  if (!containerEl)
    return;
  const rootEl = (_b = containerEl.querySelector(".bases-view")) != null ? _b : containerEl;
  const seeded = seedConfigFromView(rootEl);
  const existing = await loadConfig(app, basePath);
  let added = 0;
  for (const [col, vals] of Object.entries(seeded.columns)) {
    if (!existing.columns[col])
      existing.columns[col] = {};
    for (const [rawVal, color] of Object.entries(vals)) {
      if (!existing.columns[col][rawVal]) {
        existing.columns[col][rawVal] = color;
        added++;
      }
    }
  }
  await saveConfig(app, basePath, existing);
  const colorsPath = colorsPathFromBasePath(basePath);
  new import_obsidian.Notice(`Bases Tag Colors: added ${added} new entries to ${colorsPath} (existing colors kept)`);
}
async function cmdReloadColorConfig(app, applyToBase) {
  var _a;
  const leaf = app.workspace.activeLeaf;
  if (!leaf || ((_a = leaf.view) == null ? void 0 : _a.getViewType()) !== "bases") {
    new import_obsidian.Notice("Bases Tag Colors: open a .base file first");
    return;
  }
  const basePath = getBasePath(leaf);
  if (!basePath) {
    new import_obsidian.Notice("Bases Tag Colors: could not resolve base file path");
    return;
  }
  await applyToBase(basePath);
  new import_obsidian.Notice("Bases Tag Colors: config reloaded");
}
async function cmdMigrateFromOldPlugin(app, applyToBase) {
  var _a, _b, _c;
  const leaf = app.workspace.activeLeaf;
  if (!leaf || ((_a = leaf.view) == null ? void 0 : _a.getViewType()) !== "bases") {
    new import_obsidian.Notice("Bases Tag Colors: open a .base file first");
    return;
  }
  const basePath = getBasePath(leaf);
  if (!basePath) {
    new import_obsidian.Notice("Bases Tag Colors: could not resolve base file path");
    return;
  }
  const oldDataPath = ".obsidian/plugins/colored-bases-properties/data.json";
  const oldExists = await app.vault.adapter.exists(oldDataPath);
  if (!oldExists) {
    new import_obsidian.Notice("Bases Tag Colors: colored-bases-properties not found \u2014 nothing to migrate");
    return;
  }
  let oldPillColors = {};
  try {
    const raw = await app.vault.adapter.read(oldDataPath);
    const parsed = JSON.parse(raw);
    oldPillColors = (_b = parsed.pillColors) != null ? _b : {};
  } catch (e) {
    new import_obsidian.Notice("Bases Tag Colors: failed to read old plugin data");
    return;
  }
  const view = leaf.view;
  const containerEl = view.containerEl;
  if (!containerEl)
    return;
  const rootEl = (_c = containerEl.querySelector(".bases-view")) != null ? _c : containerEl;
  const visibleValues = /* @__PURE__ */ new Set();
  rootEl.querySelectorAll(".multi-select-pill").forEach((pill) => {
    var _a2, _b2;
    const contentEl = pill.querySelector(".multi-select-pill-content");
    const rawText = ((_b2 = (_a2 = contentEl == null ? void 0 : contentEl.textContent) != null ? _a2 : pill.textContent) != null ? _b2 : "").trim();
    if (rawText)
      visibleValues.add(rawText);
  });
  const existing = await loadConfig(app, basePath);
  let migrated = 0;
  let total = 0;
  for (const rawText of visibleValues) {
    total++;
    if (oldPillColors[rawText]) {
      if (!existing.columns["*"])
        existing.columns["*"] = {};
      existing.columns["*"][rawText] = oldPillColors[rawText];
      migrated++;
    }
  }
  await saveConfig(app, basePath, existing);
  await applyToBase(basePath);
  const colorsPath = colorsPathFromBasePath(basePath);
  new import_obsidian.Notice(`Bases Tag Colors: migrated ${migrated} of ${total} values to ${colorsPath}`);
}

// src/settings-tab.ts
var import_obsidian2 = require("obsidian");
var BasesTagColorsSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.selectedBase = "";
    this.config = { version: 1, columns: {} };
    this.searchQuery = "";
    this.debounceTimer = null;
    this.shapeSaveTimer = null;
    this.plugin = plugin;
  }
  hide() {
    if (this.debounceTimer !== null) {
      window.clearTimeout(this.debounceTimer);
      this.debounceTimer = null;
    }
    if (this.shapeSaveTimer !== null) {
      window.clearTimeout(this.shapeSaveTimer);
      this.shapeSaveTimer = null;
      this.plugin.saveSettings();
    }
  }
  async display() {
    var _a;
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("blc-settings");
    const hero = containerEl.createDiv({ cls: "blc-hero" });
    hero.createEl("p", { text: "BASES TAG COLORS", cls: "blc-hero-eyebrow" });
    hero.createDiv({ text: "Bring life to your tags.", cls: "blc-hero-title" });
    hero.createEl("p", { text: `v${this.plugin.manifest.version} By Oleg Brovchenko`, cls: "blc-hero-meta" });
    const headerEl = containerEl.createDiv({ cls: "blc-header" });
    const selectorWrapper = headerEl.createDiv({ cls: "blc-selector-wrapper" });
    selectorWrapper.createEl("label", { text: "Base:", cls: "blc-label" });
    const select = selectorWrapper.createEl("select", { cls: "blc-base-select" });
    const importBtn = headerEl.createEl("button", { text: "Import from active base", cls: "blc-import-btn mod-cta" });
    const refreshBtn = headerEl.createEl("button", { text: "Refresh", cls: "blc-refresh-btn" });
    refreshBtn.title = "Re-read the colors file and repaint \u2014 changes nothing on disk";
    const searchInput = containerEl.createEl("input", {
      type: "text",
      placeholder: "Search values\u2026",
      cls: "blc-search"
    });
    containerEl.createEl("div", { text: "Colors", cls: "blc-section-label" });
    const listEl = containerEl.createDiv({ cls: "blc-list" });
    containerEl.createEl("div", { text: "Add value", cls: "blc-section-label" });
    const addRowEl = containerEl.createDiv({ cls: "blc-add-row" });
    this.buildAddRow(addRowEl, listEl);
    containerEl.createEl("div", { text: "Pill shape", cls: "blc-section-label" });
    this.buildShapeSection(containerEl, listEl);
    containerEl.createEl("div", { text: "Auto color", cls: "blc-section-label" });
    new import_obsidian2.Setting(containerEl).setName("Auto-color unconfigured values").setDesc("Values without a configured color get a consistent generated one. Your configured colors always win.").addToggle((t) => t.setValue(this.plugin.settings.autoColor).onChange(async (v) => {
      this.plugin.settings.autoColor = v;
      await this.plugin.saveSettings();
      this.plugin.applyAutoColorToggle();
    }));
    new import_obsidian2.Setting(containerEl).setName("Color pills in note properties").setDesc("The same values get the same colors (and shape) in the Properties panel at the top of notes, merged from all your bases.").addToggle((t) => t.setValue(this.plugin.settings.propertiesColor).onChange(async (v) => {
      this.plugin.settings.propertiesColor = v;
      await this.plugin.saveSettings();
      this.plugin.applyPropertiesToggle();
    }));
    const bases = await listBasesInVault(this.app);
    if (bases.length === 0) {
      select.createEl("option", { text: "No .base files found", value: "" });
      importBtn.disabled = true;
      return;
    }
    const activeLeaf = this.app.workspace.activeLeaf;
    const activeBase = activeLeaf ? getBasePath(activeLeaf) : null;
    for (const b of bases) {
      const opt = select.createEl("option", { text: b, value: b });
      if (b === activeBase)
        opt.selected = true;
    }
    this.selectedBase = activeBase && bases.includes(activeBase) ? activeBase : bases[0];
    select.value = this.selectedBase;
    this.config = await loadConfig(this.app, this.selectedBase);
    this.renderValueList(listEl);
    select.addEventListener("change", async () => {
      this.selectedBase = select.value;
      this.config = await loadConfig(this.app, this.selectedBase);
      this.searchQuery = "";
      searchInput.value = "";
      this.renderValueList(listEl);
    });
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value.toLowerCase();
      this.filterRows(listEl);
    });
    importBtn.addEventListener("click", async () => {
      var _a2, _b;
      const leaf = this.app.workspace.activeLeaf;
      if (!leaf || ((_a2 = leaf.view) == null ? void 0 : _a2.getViewType()) !== "bases") {
        importBtn.title = "No bases view open";
        return;
      }
      const activeBase2 = getBasePath(leaf);
      if (activeBase2 !== this.selectedBase) {
        importBtn.title = `Active base doesn't match \u2014 open "${this.selectedBase}" first`;
        new import_obsidian2.Notice(`Import aborted: active view is a different base. Click the "${this.selectedBase}" tab first.`);
        return;
      }
      const view = leaf.view;
      const containerEl2 = view.containerEl;
      if (!containerEl2)
        return;
      const rootEl = (_b = containerEl2.querySelector(".bases-view")) != null ? _b : containerEl2;
      const seeded = seedConfigFromView(rootEl);
      const allowedCols = await parseBaseColumns(this.app, this.selectedBase);
      for (const [col, vals] of Object.entries(seeded.columns)) {
        if (allowedCols && col !== "*" && !allowedCols.has(col))
          continue;
        if (!this.config.columns[col])
          this.config.columns[col] = {};
        for (const [rawVal, color] of Object.entries(vals)) {
          if (!this.config.columns[col][rawVal]) {
            this.config.columns[col][rawVal] = color;
          }
        }
      }
      await this.saveAndApply();
      this.renderValueList(listEl);
    });
    refreshBtn.addEventListener("click", async () => {
      if (!this.selectedBase)
        return;
      this.config = await loadConfig(this.app, this.selectedBase);
      this.renderValueList(listEl);
      await this.plugin.applyToBase(this.selectedBase);
      new import_obsidian2.Notice("Bases Tag Colors: refreshed");
    });
    this.updateImportBtnState(importBtn);
    containerEl.createEl("hr", { cls: "blc-landing-divider" });
    const featuresSection = containerEl.createDiv({ cls: "blc-features" });
    featuresSection.createEl("p", { text: "WHAT IT DOES", cls: "blc-section-eyebrow" });
    const grid = featuresSection.createDiv({ cls: "blc-features-grid" });
    [
      { title: "Auto base detection", body: "Automatically detects your active base." },
      { title: "Visual settings UI", body: "Color picker, hex input, search bar." },
      { title: "Live in 100ms", body: "Edit the color, real time update." },
      { title: "Per-base palettes", body: "Each .base file gets a sibling .colors.json." }
    ].forEach((f) => {
      const item = grid.createDiv({ cls: "blc-feature-item" });
      item.createDiv({ text: f.title, cls: "blc-feature-title" });
      item.createEl("p", { text: f.body, cls: "blc-feature-body" });
    });
    const problemSection = containerEl.createDiv({ cls: "blc-text-section" });
    problemSection.createEl("p", { text: "THE PROBLEM", cls: "blc-section-eyebrow" });
    problemSection.createEl("p", { text: "Obsidian Bases have zero native pill colors. It makes reading extremely hard, especially annoying if you are coming from Notion and you are used to having colors on your tags.", cls: "blc-text-body" });
    const previewSection = containerEl.createDiv({ cls: "blc-text-section" });
    previewSection.createEl("p", { text: "PREVIEW", cls: "blc-section-eyebrow" });
    const windowFrame = previewSection.createDiv({ cls: "blc-window-frame" });
    const windowChrome = windowFrame.createDiv({ cls: "blc-window-chrome" });
    const dotsWrap = windowChrome.createDiv({ cls: "blc-window-dots" });
    dotsWrap.createDiv({ cls: "blc-dot blc-dot-red" });
    dotsWrap.createDiv({ cls: "blc-dot blc-dot-yellow" });
    dotsWrap.createDiv({ cls: "blc-dot blc-dot-green" });
    windowChrome.createEl("span", { text: "YouTube Ideas.base", cls: "blc-window-title" });
    const img = windowFrame.createEl("img", { cls: "blc-preview-img", attr: { alt: "Bases Tag Colors in action" } });
    const pluginDir = (_a = this.plugin.manifest.dir) != null ? _a : ".obsidian/plugins/bases-tag-colors";
    img.src = this.app.vault.adapter.getResourcePath(`${pluginDir}/preview.png`);
    containerEl.createEl("p", { text: "Enjoy! \u2014 Oleg Brovchenko", cls: "blc-signoff" });
  }
  // Global pill shape controls: toggle + sliders, applied live to all bases views
  // and mirrored on the pill previews in the color list above.
  // Sliders fire per drag tick — styles apply immediately, disk write is debounced.
  buildShapeSection(containerEl, listEl) {
    const shape = this.plugin.settings;
    new import_obsidian2.Setting(containerEl).setName("Customize pill shape").setDesc("Notion-style pill shape for Bases views: comfortable padding, mid-hard corners. Turn off to use your theme's default shape.").addToggle((t) => t.setValue(shape.customShape).onChange(async (v) => {
      shape.customShape = v;
      await this.plugin.saveSettings();
      renderSliders();
      this.applyPreviewShape(listEl);
    }));
    const slidersEl = containerEl.createDiv();
    const sliderDefs = [
      { name: "Horizontal padding", desc: "Space left and right of the tag text.", min: 2, max: 18, key: "paddingX" },
      { name: "Vertical padding", desc: "Space above and below the tag text.", min: 0, max: 10, key: "paddingY" },
      { name: "Corner radius", desc: "0 = square, higher = rounder.", min: 0, max: 24, key: "borderRadius" }
    ];
    const renderSliders = () => {
      slidersEl.empty();
      if (!shape.customShape)
        return;
      for (const def of sliderDefs) {
        new import_obsidian2.Setting(slidersEl).setName(def.name).setDesc(def.desc).addSlider((s) => s.setLimits(def.min, def.max, 1).setValue(shape[def.key]).setDynamicTooltip().onChange((v) => {
          shape[def.key] = v;
          this.plugin.applyShape();
          this.applyPreviewShape(listEl);
          this.debouncedSaveShape();
        }));
      }
    };
    renderSliders();
    this.applyPreviewShape(listEl);
  }
  debouncedSaveShape() {
    if (this.shapeSaveTimer !== null)
      window.clearTimeout(this.shapeSaveTimer);
    this.shapeSaveTimer = window.setTimeout(() => {
      this.shapeSaveTimer = null;
      this.plugin.saveSettings();
    }, 150);
  }
  applyPreviewShape(listEl) {
    const shape = this.plugin.settings;
    listEl.querySelectorAll(".blc-pill-preview").forEach((el) => {
      if (shape.customShape) {
        el.setCssStyles({
          padding: `${shape.paddingY}px ${shape.paddingX}px`,
          borderRadius: `${shape.borderRadius}px`
        });
      } else {
        el.setCssStyles({ padding: "", borderRadius: "" });
      }
    });
  }
  updateImportBtnState(btn) {
    var _a;
    const leaf = this.app.workspace.activeLeaf;
    const isBasesView = ((_a = leaf == null ? void 0 : leaf.view) == null ? void 0 : _a.getViewType()) === "bases";
    btn.disabled = !isBasesView;
    btn.title = isBasesView ? "Import all visible pill values from the active base" : "No bases view open";
  }
  renderValueList(listEl) {
    listEl.empty();
    const entries = [];
    for (const [col, vals] of Object.entries(this.config.columns)) {
      for (const [rawValue, color] of Object.entries(vals)) {
        entries.push({ col, rawValue, color });
      }
    }
    const valuesWithSpecificCol = new Set(
      entries.filter((e) => e.col !== "*").map((e) => e.rawValue)
    );
    const deduped = entries.filter((e) => !(e.col === "*" && valuesWithSpecificCol.has(e.rawValue)));
    deduped.sort((a, b) => {
      if (a.col === "*" && b.col !== "*")
        return -1;
      if (a.col !== "*" && b.col === "*")
        return 1;
      if (a.col !== b.col)
        return a.col.localeCompare(b.col);
      return a.rawValue.localeCompare(b.rawValue);
    });
    if (deduped.length === 0) {
      listEl.createEl("p", { text: "No colors configured. Import from active base or add manually below.", cls: "blc-empty" });
      return;
    }
    for (const entry of deduped) {
      this.buildRow(listEl, entry.col, entry.rawValue, entry.color);
    }
    this.filterRows(listEl);
    this.applyPreviewShape(listEl);
  }
  buildRow(listEl, col, rawValue, color) {
    const row = listEl.createDiv({ cls: "blc-row" });
    row.dataset.col = col;
    row.dataset.value = rawValue.toLowerCase();
    const pillPreview = row.createEl("span", { text: rawValue, cls: "blc-pill-preview" });
    pillPreview.setCssStyles({ backgroundColor: color });
    row.createEl("span", { text: col === "*" ? "any column" : col, cls: "blc-col-badge" });
    row.createDiv({ cls: "blc-spacer" });
    const picker = row.createEl("input", { cls: "blc-color-picker" });
    picker.type = "color";
    picker.value = color;
    const hexInput = row.createEl("input", { cls: "blc-hex-input" });
    hexInput.type = "text";
    hexInput.maxLength = 7;
    hexInput.value = color;
    hexInput.placeholder = "#rrggbb";
    const removeBtn = row.createEl("button", { text: "\xD7", cls: "blc-remove-btn" });
    picker.addEventListener("input", () => {
      hexInput.value = picker.value;
      pillPreview.setCssStyles({ backgroundColor: picker.value });
      this.setColor(col, rawValue, picker.value);
      this.debouncedSaveApply();
    });
    hexInput.addEventListener("blur", () => {
      const val = hexInput.value.trim();
      if (/^#[0-9a-fA-F]{6}$/.test(val)) {
        picker.value = val;
        pillPreview.setCssStyles({ backgroundColor: val });
        this.setColor(col, rawValue, val);
        this.saveAndApply();
      } else {
        hexInput.value = picker.value;
      }
    });
    removeBtn.addEventListener("click", async () => {
      this.deleteColor(col, rawValue);
      await this.saveAndApply();
      row.remove();
    });
  }
  buildAddRow(addRowEl, listEl) {
    const nameInput = addRowEl.createEl("input", { cls: "blc-add-name" });
    nameInput.type = "text";
    nameInput.placeholder = "Value name";
    const picker = addRowEl.createEl("input", { cls: "blc-color-picker" });
    picker.type = "color";
    picker.value = "#78b7b8";
    const hexInput = addRowEl.createEl("input", { cls: "blc-hex-input" });
    hexInput.type = "text";
    hexInput.maxLength = 7;
    hexInput.value = "#78b7b8";
    hexInput.placeholder = "#rrggbb";
    picker.addEventListener("input", () => {
      hexInput.value = picker.value;
    });
    hexInput.addEventListener("blur", () => {
      if (/^#[0-9a-fA-F]{6}$/.test(hexInput.value.trim())) {
        picker.value = hexInput.value.trim();
      } else {
        hexInput.value = picker.value;
      }
    });
    const addBtn = addRowEl.createEl("button", { text: "+ Add", cls: "blc-add-btn" });
    addBtn.addEventListener("click", async () => {
      const name = nameInput.value.trim();
      if (!name)
        return;
      const color = picker.value;
      if (!this.config.columns["*"])
        this.config.columns["*"] = {};
      this.config.columns["*"][name] = color;
      await this.saveAndApply();
      this.buildRow(listEl, "*", name, color);
      this.filterRows(listEl);
      nameInput.value = "";
      picker.value = "#78b7b8";
      hexInput.value = "#78b7b8";
    });
  }
  filterRows(listEl) {
    const q = this.searchQuery;
    listEl.querySelectorAll(".blc-row").forEach((row) => {
      var _a, _b;
      const valueText = (_a = row.dataset.value) != null ? _a : "";
      const colText = (_b = row.dataset.col) != null ? _b : "";
      const matches = !q || valueText.includes(q) || colText.includes(q);
      row.toggleClass("blc-row-hidden", !matches);
    });
  }
  setColor(col, rawValue, color) {
    if (!this.config.columns[col])
      this.config.columns[col] = {};
    this.config.columns[col][rawValue] = color;
  }
  deleteColor(col, rawValue) {
    if (!this.config.columns[col])
      return;
    delete this.config.columns[col][rawValue];
    if (Object.keys(this.config.columns[col]).length === 0) {
      delete this.config.columns[col];
    }
  }
  debouncedSaveApply() {
    if (this.debounceTimer !== null)
      window.clearTimeout(this.debounceTimer);
    this.debounceTimer = window.setTimeout(() => {
      this.debounceTimer = null;
      this.saveAndApply();
    }, 150);
  }
  async saveAndApply() {
    if (!this.selectedBase)
      return;
    await saveConfig(this.app, this.selectedBase, this.config);
    await this.plugin.applyToBase(this.selectedBase);
  }
};

// main.ts
function mutationsAddPills(mutations) {
  return mutations.some(
    (m) => m.type === "childList" && Array.from(m.addedNodes).some((node) => {
      var _a;
      if (node.nodeType !== Node.ELEMENT_NODE)
        return false;
      const el = node;
      return el.classList.contains("multi-select-pill") || ((_a = el.querySelector) == null ? void 0 : _a.call(el, ".multi-select-pill")) !== null;
    })
  );
}
function mutationsAddBasesEmbeds(mutations) {
  return mutations.some(
    (m) => m.type === "childList" && Array.from(m.addedNodes).some(
      (node) => node.nodeType === Node.ELEMENT_NODE && containsBasesEmbed(node)
    )
  );
}
var BasesTagColorsPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.activeLeaves = /* @__PURE__ */ new Map();
    this.embedLeaves = /* @__PURE__ */ new Map();
    // Base paths whose colors were loaded because an embed shows them
    this.embedBasePaths = /* @__PURE__ */ new Set();
    this.layoutDebounce = null;
    this.colorsModifyDebounce = /* @__PURE__ */ new Map();
    this.propsObserver = null;
    this.settings = { ...DEFAULT_SETTINGS };
  }
  async onload() {
    this.styles = new StyleManager();
    const stored = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    for (const key of ["paddingX", "paddingY", "borderRadius"]) {
      if (!Number.isFinite(stored[key]))
        stored[key] = DEFAULT_SETTINGS[key];
    }
    stored.customShape = !!stored.customShape;
    stored.autoColor = !!stored.autoColor;
    stored.propertiesColor = !!stored.propertiesColor;
    this.settings = stored;
    this.styles.setShape(this.settings);
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        var _a;
        if (!leaf)
          return;
        if (((_a = leaf.view) == null ? void 0 : _a.getViewType()) === "bases") {
          this.activateLeaf(leaf);
        } else if (leaf.view instanceof import_obsidian3.MarkdownView) {
          this.activateEmbedLeaf(leaf);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        if (this.layoutDebounce !== null)
          window.clearTimeout(this.layoutDebounce);
        this.layoutDebounce = window.setTimeout(() => {
          this.layoutDebounce = null;
          this.syncLeaves();
        }, 50);
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (!(file instanceof import_obsidian3.TFile))
          return;
        if (!file.path.endsWith(".colors.json"))
          return;
        const prev = this.colorsModifyDebounce.get(file.path);
        if (prev !== void 0)
          window.clearTimeout(prev);
        const timer = window.setTimeout(() => {
          this.colorsModifyDebounce.delete(file.path);
          const basePath = basePathFromColorsPath(file.path);
          this.applyToBase(basePath);
          this.reloadPropertyConfigs();
        }, 100);
        this.colorsModifyDebounce.set(file.path, timer);
      })
    );
    this.addCommand({
      id: "open-color-config",
      name: "Open color config for current base",
      callback: () => cmdOpenColorConfig(this.app)
    });
    this.addCommand({
      id: "seed-from-current-base",
      name: "Seed config from current base values",
      callback: () => cmdSeedFromCurrentBase(this.app)
    });
    this.addCommand({
      id: "reload-color-config",
      name: "Reload color config",
      callback: () => cmdReloadColorConfig(this.app, this.applyToBase.bind(this))
    });
    this.addCommand({
      id: "migrate-from-colored-bases-properties",
      name: "Migrate from colored-bases-properties (current base)",
      callback: () => cmdMigrateFromOldPlugin(this.app, this.applyToBase.bind(this))
    });
    this.addSettingTab(new BasesTagColorsSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.syncLeaves();
      if (this.settings.propertiesColor)
        this.startPropertiesColoring();
    });
  }
  // Watch a view root for virtualised rows adding pills, re-stamp when they appear
  createPillObserver(rootEl, basePath) {
    const observer = new MutationObserver((mutations) => {
      if (mutationsAddPills(mutations))
        this.refreshView(rootEl, basePath);
    });
    observer.observe(rootEl, { childList: true, subtree: true });
    return observer;
  }
  // D3: load config, register colors, stamp + paint pills, wire observer
  async activateLeaf(leaf) {
    const basePath = getBasePath(leaf);
    if (!basePath) {
      console.warn("[BasesTagColors] bases view active but path unavailable");
      return;
    }
    const existing = this.activeLeaves.get(leaf);
    if (existing && existing.basePath === basePath) {
      await this.applyToBase(basePath);
      return;
    }
    if (existing)
      this.deactivateLeaf(leaf);
    const rootEl = tagLeaf(leaf, basePath);
    if (!rootEl)
      return;
    const config = await loadConfig(this.app, basePath);
    const raced = this.activeLeaves.get(leaf);
    if (raced && raced.basePath === basePath)
      return;
    this.styles.setColorsForBase(basePath, config);
    this.refreshView(rootEl, basePath);
    const observer = this.createPillObserver(rootEl, basePath);
    this.activeLeaves.set(leaf, { basePath, rootEl, observer });
  }
  deactivateLeaf(leaf) {
    const state = this.activeLeaves.get(leaf);
    if (!state)
      return;
    state.observer.disconnect();
    this.sweepPillAttrs(state.rootEl);
    untagLeaf(leaf);
    this.activeLeaves.delete(leaf);
    const stillOpen = [...this.activeLeaves.values()].some((s) => s.basePath === state.basePath) || this.embedBasePaths.has(state.basePath);
    if (!stillOpen)
      this.styles.clearColorsForBase(state.basePath);
  }
  // Re-tag + re-apply all current bases leaves and markdown leaves (for
  // their embedded bases); clean up closed ones
  syncLeaves() {
    const current = new Set(this.app.workspace.getLeavesOfType("bases"));
    for (const leaf of [...this.activeLeaves.keys()]) {
      if (!current.has(leaf))
        this.deactivateLeaf(leaf);
    }
    for (const leaf of current) {
      if (!this.activeLeaves.has(leaf))
        this.activateLeaf(leaf);
    }
    const mdCurrent = new Set(this.app.workspace.getLeavesOfType("markdown"));
    for (const leaf of [...this.embedLeaves.keys()]) {
      if (!mdCurrent.has(leaf))
        this.deactivateEmbedLeaf(leaf);
    }
    for (const leaf of mdCurrent) {
      if (this.embedLeaves.has(leaf)) {
        this.refreshEmbedLeaf(leaf);
      } else {
        this.activateEmbedLeaf(leaf);
      }
    }
    this.pruneEmbedBasePaths();
  }
  // ── Embedded bases (![[Something.base]] inside notes) ────────────────
  // Every markdown leaf gets an observer: embeds render lazily on scroll and
  // appear when the user types one, so watching only leaves that currently
  // hold an embed would miss both.
  activateEmbedLeaf(leaf) {
    if (this.embedLeaves.has(leaf)) {
      this.refreshEmbedLeaf(leaf);
      return;
    }
    const view = leaf.view;
    if (!(view instanceof import_obsidian3.MarkdownView))
      return;
    const observer = new MutationObserver((mutations) => {
      if (mutationsAddPills(mutations) || mutationsAddBasesEmbeds(mutations)) {
        this.refreshEmbedLeaf(leaf);
      }
    });
    observer.observe(view.containerEl, { childList: true, subtree: true });
    this.embedLeaves.set(leaf, { observer });
    this.refreshEmbedLeaf(leaf);
  }
  deactivateEmbedLeaf(leaf) {
    const state = this.embedLeaves.get(leaf);
    if (!state)
      return;
    state.observer.disconnect();
    const containerEl = leaf.view instanceof import_obsidian3.MarkdownView ? leaf.view.containerEl : null;
    if (containerEl) {
      this.sweepPillAttrs(containerEl);
      containerEl.querySelectorAll("[data-bases-tag-colors-id]").forEach((el) => el.removeAttribute("data-bases-tag-colors-id"));
    }
    this.embedLeaves.delete(leaf);
  }
  // Unpaint + unstamp every pill under root (leaf teardown for both leaf kinds)
  sweepPillAttrs(root) {
    root.querySelectorAll("[data-blc-value], [data-blc-col]").forEach((el) => {
      this.styles.unpaintPill(el);
      el.removeAttribute("data-blc-value");
      el.removeAttribute("data-blc-col");
    });
  }
  // Tag every embed in the leaf, load config for bases seen the first time,
  // then stamp + paint. Keyed by base path, so the standalone view, split
  // panes and several embeds of one base all share the same colors.
  async refreshEmbedLeaf(leaf) {
    const view = leaf.view;
    if (!(view instanceof import_obsidian3.MarkdownView) || !view.file)
      return;
    const roots = tagEmbeds(this.app, view.containerEl, view.file.path);
    for (const [basePath, rootEls] of roots.entries()) {
      if (!this.embedBasePaths.has(basePath)) {
        this.embedBasePaths.add(basePath);
        const config = await loadConfig(this.app, basePath);
        this.styles.setColorsForBase(basePath, config);
      }
      for (const rootEl of rootEls)
        this.refreshView(rootEl, basePath);
    }
  }
  // Drop stored colors for bases no longer shown by any embed or leaf
  pruneEmbedBasePaths() {
    const alive = /* @__PURE__ */ new Set();
    for (const leaf of this.embedLeaves.keys()) {
      const view = leaf.view;
      if (!(view instanceof import_obsidian3.MarkdownView))
        continue;
      view.containerEl.querySelectorAll("[data-bases-tag-colors-id]").forEach((el) => {
        const p = el.getAttribute("data-bases-tag-colors-id");
        if (p)
          alive.add(p);
      });
    }
    for (const basePath of [...this.embedBasePaths]) {
      if (alive.has(basePath))
        continue;
      this.embedBasePaths.delete(basePath);
      const stillOpen = [...this.activeLeaves.values()].some((s) => s.basePath === basePath);
      if (!stillOpen)
        this.styles.clearColorsForBase(basePath);
    }
  }
  // D3: re-apply styles + re-process pills for all leaves showing basePath.
  // Re-queries rootEl on every call — guards against DOM refresh (e.g. after Settings close).
  async applyToBase(basePath) {
    const config = await loadConfig(this.app, basePath);
    this.styles.setColorsForBase(basePath, config);
    for (const [leaf, state] of this.activeLeaves.entries()) {
      if (state.basePath !== basePath)
        continue;
      const freshRoot = tagLeaf(leaf, basePath);
      if (!freshRoot)
        continue;
      if (freshRoot !== state.rootEl) {
        state.observer.disconnect();
        state.rootEl = freshRoot;
        state.observer = this.createPillObserver(freshRoot, basePath);
      }
      this.refreshView(state.rootEl, basePath);
    }
  }
  // Apply the current shape to open views without touching disk (live slider feedback)
  applyShape() {
    this.styles.setShape(this.settings);
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.styles.setShape(this.settings);
  }
  // Called when the auto-color toggle flips: drop generated rules, re-collect
  // from every active view (collection is a no-op while the toggle is off)
  applyAutoColorToggle() {
    if (!this.settings.autoColor) {
      this.styles.clearAllAutoColors();
      return;
    }
    for (const state of this.activeLeaves.values()) {
      this.refreshView(state.rootEl, state.basePath);
    }
    for (const leaf of this.embedLeaves.keys())
      this.refreshEmbedLeaf(leaf);
    if (this.settings.propertiesColor)
      this.processPropertyPills();
  }
  // Stamp pills, register their values for auto colors when enabled, then paint
  refreshView(rootEl, basePath) {
    const values = processBaseView(rootEl);
    if (this.settings.autoColor) {
      this.styles.addAutoValuesForBase(basePath, values);
    }
    this.styles.paintView(rootEl, basePath);
  }
  // ── Note Properties coloring ─────────────────────────────────────────
  applyPropertiesToggle() {
    if (this.settings.propertiesColor) {
      this.startPropertiesColoring();
    } else {
      this.stopPropertiesColoring();
    }
    this.styles.setShape(this.settings);
  }
  startPropertiesColoring() {
    if (this.propsObserver)
      return;
    this.propsObserver = new MutationObserver((mutations) => {
      if (mutationsAddPills(mutations))
        this.processPropertyPills();
    });
    this.propsObserver.observe(document.body, { childList: true, subtree: true });
    this.processPropertyPills();
    this.reloadPropertyConfigs();
  }
  stopPropertiesColoring() {
    if (!this.propsObserver)
      return;
    this.propsObserver.disconnect();
    this.propsObserver = null;
    document.body.querySelectorAll(".metadata-property .multi-select-pill[data-blc-value]").forEach((el) => {
      this.styles.unpaintPill(el);
      el.removeAttribute("data-blc-value");
    });
    this.styles.clearPropertyColors();
  }
  // Stamp pills in every visible Properties panel. Column matching rides the
  // panel's own data-property-key attribute, so only the value is stamped.
  processPropertyPills() {
    const values = [];
    document.body.querySelectorAll(".metadata-property .multi-select-pill").forEach((pill) => {
      var _a, _b;
      const contentEl = pill.querySelector(".multi-select-pill-content");
      const rawText = ((_b = (_a = contentEl == null ? void 0 : contentEl.textContent) != null ? _a : pill.textContent) != null ? _b : "").trim();
      if (!rawText)
        return;
      const sanitized = sanitizeValue(rawText);
      if (!sanitized)
        return;
      pill.setAttribute("data-blc-value", sanitized);
      values.push(sanitized);
    });
    if (this.settings.autoColor && values.length) {
      this.styles.addPropertyAutoValues(values);
    }
    this.styles.paintProperties();
  }
  async reloadPropertyConfigs() {
    if (!this.settings.propertiesColor)
      return;
    const colorsFiles = this.app.vault.getFiles().filter((f) => f.path.endsWith(".colors.json"));
    const configs = await Promise.all(
      colorsFiles.map((f) => loadConfig(this.app, basePathFromColorsPath(f.path)))
    );
    this.styles.setPropertyColors(configs);
  }
  onunload() {
    if (this.layoutDebounce !== null) {
      window.clearTimeout(this.layoutDebounce);
      this.layoutDebounce = null;
    }
    for (const timer of this.colorsModifyDebounce.values())
      window.clearTimeout(timer);
    this.colorsModifyDebounce.clear();
    for (const leaf of [...this.activeLeaves.keys()])
      this.deactivateLeaf(leaf);
    for (const leaf of [...this.embedLeaves.keys()])
      this.deactivateEmbedLeaf(leaf);
    this.embedBasePaths.clear();
    this.stopPropertiesColoring();
    this.styles.destroy();
  }
};
